#!/bin/bash
# ═══════════════════════════════════════════════════════════════
#  SCHULTE TUNISIA — Share with Professor via ngrok Tunnels
# ═══════════════════════════════════════════════════════════════
#
#  Run your apps first:
#    1. backend   -> cd backend   && npm run dev
#    2. candidate -> cd candidate && npm run start   (recommended)
#    3. hr        -> cd hr        && npm run preview -- --host 0.0.0.0 --port 8080 --strictPort
#
#  Then run: bash tunnel-share.sh
#
#  This script creates 3 ngrok HTTP tunnels and updates front-end env files
#  so Candidate + HR use the public backend URL.
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TUNNEL_LOG_DIR="$SCRIPT_DIR/.tunnel-logs"
mkdir -p "$TUNNEL_LOG_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  SCHULTE TUNISIA — ngrok Tunnel Sharing${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""

if ! command -v ngrok >/dev/null 2>&1; then
  echo -e "${RED}✗ ngrok not found. Install/configure ngrok first.${NC}"
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo -e "${RED}✗ jq not found. Install jq first (sudo apt install jq).${NC}"
  exit 1
fi

echo -e "${YELLOW}▸ Checking local services...${NC}"

check_port() {
  local port="$1"
  local name="$2"
  if curl -s --max-time 3 "http://localhost:$port" >/dev/null 2>&1 || \
     curl -s --max-time 3 "http://localhost:$port/api/health" >/dev/null 2>&1; then
    echo -e "  ${GREEN}✓${NC} $name is running on port $port"
    return 0
  fi

  echo -e "  ${RED}✗${NC} $name is NOT running on port $port"
  return 1
}

ALL_RUNNING=true
check_port 4000 "Backend API"   || ALL_RUNNING=false
check_port 3000 "Candidate App" || ALL_RUNNING=false
check_port 8080 "HR/Admin App"  || ALL_RUNNING=false

if [ "$ALL_RUNNING" = false ]; then
  echo ""
  echo -e "${RED}✗ Some services are not running. Start them first.${NC}"
  exit 1
fi

echo ""
echo -e "${GREEN}✓ All 3 services running!${NC}"
echo ""

# Clean previous tunnel agents to avoid conflicts/session limits.
pkill -f "cloudflared tunnel --url" 2>/dev/null || true
pkill -f "ngrok start --all" 2>/dev/null || true
pkill -f "ngrok http" 2>/dev/null || true
sleep 1

BASE_CFG=$(ngrok config check 2>/dev/null | sed -n 's/^Valid configuration file at //p')
if [ -z "$BASE_CFG" ] || [ ! -f "$BASE_CFG" ]; then
  echo -e "${RED}✗ Could not locate valid ngrok base config.${NC}"
  echo -e "  Run: ${CYAN}ngrok config check${NC}"
  exit 1
fi

GENERATED_CFG="$TUNNEL_LOG_DIR/ngrok-generated.yml"
NGROK_LOG="$TUNNEL_LOG_DIR/ngrok.log"

cat > "$GENERATED_CFG" <<EOF_CFG
version: "3"
agent:
  web_addr: 127.0.0.1:4040
tunnels:
  backend:
    proto: http
    addr: 4000
  candidate:
    proto: http
    addr: 3000
  hr:
    proto: http
    addr: 8080
EOF_CFG

echo -e "${YELLOW}▸ Starting ngrok tunnels...${NC}"
nohup ngrok start --all --config "$BASE_CFG","$GENERATED_CFG" --log "$NGROK_LOG" --log-format json --log-level info >/dev/null 2>&1 &
NGROK_PID=$!

get_url_by_name() {
  local tunnel_name="$1"
  local timeout=40
  local elapsed=0

  while [ "$elapsed" -lt "$timeout" ]; do
    if ! kill -0 "$NGROK_PID" 2>/dev/null; then
      break
    fi

    local url
    url=$(curl -s http://127.0.0.1:4040/api/tunnels 2>/dev/null \
      | jq -r --arg name "$tunnel_name" '.tunnels[]? | select(.name == $name) | .public_url' \
      | grep -E '^https://.+' \
      | head -1 || true)

    if [ -n "$url" ]; then
      echo "$url"
      return 0
    fi

    sleep 1
    elapsed=$((elapsed + 1))
  done

  return 1
}

BACKEND_URL=$(get_url_by_name backend || true)
CANDIDATE_URL=$(get_url_by_name candidate || true)
HR_URL=$(get_url_by_name hr || true)

if [ -z "${BACKEND_URL:-}" ] || [ -z "${CANDIDATE_URL:-}" ] || [ -z "${HR_URL:-}" ]; then
  echo -e "${RED}✗ Failed to get ngrok tunnel URLs.${NC}"
  echo -e "${YELLOW}Last ngrok logs:${NC}"
  tail -n 30 "$NGROK_LOG" 2>/dev/null || true
  kill "$NGROK_PID" 2>/dev/null || true
  exit 1
fi

# Backup then write frontend envs.
[ -f "$SCRIPT_DIR/candidate/.env.local" ] && cp "$SCRIPT_DIR/candidate/.env.local" "$SCRIPT_DIR/candidate/.env.local.backup"
cat > "$SCRIPT_DIR/candidate/.env.local" <<EOF_CAND
# Auto-generated by tunnel-share.sh — $(date)
NEXT_PUBLIC_API_URL=${BACKEND_URL}/api
NEXT_PUBLIC_SOCKET_URL=${BACKEND_URL}
EOF_CAND

[ -f "$SCRIPT_DIR/hr/.env.local" ] && cp "$SCRIPT_DIR/hr/.env.local" "$SCRIPT_DIR/hr/.env.local.backup"
cat > "$SCRIPT_DIR/hr/.env.local" <<EOF_HR
# Auto-generated by tunnel-share.sh — $(date)
VITE_API_URL=${BACKEND_URL}/api
EOF_HR

cat > "$TUNNEL_LOG_DIR/run.env" <<EOF_RUN
PROVIDER=ngrok
NGROK_PID=$NGROK_PID
NGROK_LOG=$NGROK_LOG
BACKEND_URL=$BACKEND_URL
CANDIDATE_URL=$CANDIDATE_URL
HR_URL=$HR_URL
EOF_RUN

echo ""
echo -e "${GREEN}✓ ngrok tunnels are active and env files updated.${NC}"
echo -e "${YELLOW}${BOLD}Important:${NC} Restart ${BOLD}candidate${NC} and ${BOLD}hr${NC} now to reload env values."
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  SHARE THESE LINKS WITH YOUR PROFESSOR${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}${BOLD}Candidate App:${NC}"
echo -e "  ${CYAN}${CANDIDATE_URL}${NC}"
echo ""
echo -e "  ${GREEN}${BOLD}HR/Admin App:${NC}"
echo -e "  ${CYAN}${HR_URL}${NC}"
echo ""
echo -e "  ${YELLOW}Internal backend tunnel used by apps:${NC}"
echo -e "  ${CYAN}${BACKEND_URL}${NC}"
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "${YELLOW}Stop sharing later with:${NC} ${BOLD}bash tunnel-stop.sh${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo ""
