#!/bin/bash
# Stop ngrok/cloudflared processes and restore local env files.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TUNNEL_LOG_DIR="$SCRIPT_DIR/.tunnel-logs"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${YELLOW}▸ Stopping tunnel processes...${NC}"

if [ -f "$TUNNEL_LOG_DIR/run.env" ]; then
  # shellcheck disable=SC1090
  source "$TUNNEL_LOG_DIR/run.env"
  if [ -n "${NGROK_PID:-}" ]; then
    kill "$NGROK_PID" 2>/dev/null || true
  fi
fi

pkill -f "ngrok start --all" 2>/dev/null || true
pkill -f "ngrok http" 2>/dev/null || true
pkill -f "cloudflared tunnel --url" 2>/dev/null || true

echo -e "${YELLOW}▸ Restoring local env files...${NC}"

restore_or_remove_env() {
  local target="$1"
  local backup="$2"

  if [ -f "$backup" ]; then
    cp "$backup" "$target"
    rm -f "$backup"
    echo -e "  ${GREEN}✓${NC} Restored $(basename "$target") from backup"
    return
  fi

  if [ -f "$target" ]; then
    if head -n 1 "$target" | grep -q "Auto-generated by tunnel-share.sh"; then
      rm -f "$target"
      echo -e "  ${GREEN}✓${NC} Removed generated $(basename "$target")"
    fi
  fi
}

restore_or_remove_env "$SCRIPT_DIR/candidate/.env.local" "$SCRIPT_DIR/candidate/.env.local.backup"
restore_or_remove_env "$SCRIPT_DIR/hr/.env.local" "$SCRIPT_DIR/hr/.env.local.backup"

if [ -f "$SCRIPT_DIR/backend/.env.local-backup" ]; then
  cp "$SCRIPT_DIR/backend/.env.local-backup" "$SCRIPT_DIR/backend/.env"
  rm -f "$SCRIPT_DIR/backend/.env.local-backup"
  echo -e "  ${GREEN}✓${NC} Restored backend/.env from legacy backup"
fi

rm -rf "$TUNNEL_LOG_DIR" 2>/dev/null || true

echo ""
echo -e "${GREEN}✓ All tunnels stopped and sharing env restored.${NC}"
echo -e "${YELLOW}  Restart candidate/hr apps to return to localhost mode.${NC}"
echo ""
