import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["'DM Sans'", 'sans-serif'],
        mono: ["'JetBrains Mono'", 'monospace'],
      },
      colors: {
        page: "var(--page)",
        card2: "var(--card2)",
        border2: "var(--border2)",
        ink: "var(--ink)",
        ink2: "var(--ink2)",
        ink3: "var(--ink3)",
        ink4: "var(--ink4)",
        v: "var(--v)",
        vl: "var(--vl)",
        vb: "var(--vb)",
        vh: "var(--vh)",
        tan: "var(--tan)",
        tanl: "var(--tanl)",
        tanb: "var(--tanb)",
        bou: "var(--bou)",
        boul: "var(--boul)",
        boub: "var(--boub)",
        zag: "var(--zag)",
        zagl: "var(--zagl)",
        zagb: "var(--zagb)",
        ok: "var(--ok)",
        okl: "var(--okl)",
        okb: "var(--okb)",
        warn: "var(--warn)",
        warnl: "var(--warnl)",
        warnb: "var(--warnb)",
        err: "var(--err)",
        errl: "var(--errl)",
        errb: "var(--errb)",
        violet: "var(--v)",
        violetl: "var(--vl)",
        violetb: "var(--vb)",
        violeth: "var(--vh)",
        coral: "var(--tan)",
        corall: "var(--tanl)",
        coralb: "var(--tanb)",
        s0: "var(--s0)",
        s1: "var(--s1)",
        s2: "var(--s2)",
        s3: "var(--s3)",
        s4: "var(--s4)",
        s5: "var(--s5)",
        acc: "var(--acc)",
        acch: "var(--acc-h)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        success: {
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
        },
        bouarada: "var(--bouarada)",
        zaghouan: "var(--zaghouan)",
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
          muted: "var(--sidebar-muted)",
        },
      },
      borderRadius: {
        xl: '12px',
        lg: '10px',
        md: '8px',
        sm: '4px',
        full: '999px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(15,13,28,0.05)',
        lift: '0 4px 14px rgba(15,13,28,0.08)',
        hover: '0 6px 18px rgba(15,13,28,0.09)',
        drag: '0 8px 24px rgba(15,13,28,0.10)',
        modal: '0 20px 48px rgba(15,13,28,0.14)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        npulse: {
          "0%,100%": { boxShadow: '0 0 0 4px #EEEDFE' },
          "50%": { boxShadow: '0 0 0 8px #EEEDFE' },
        },
        slideDown: {
          from: { transform: 'translateY(-8px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        slideIn: {
          from: { transform: 'translateX(20px)', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        npulse: 'npulse 2s ease-in-out infinite',
        slideDown: 'slideDown 200ms ease-out',
        slideIn: 'slideIn 200ms ease-out',
        fadeIn: 'fadeIn 150ms ease-out',
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
