import type { JobOffer, Application, Notification, UserProfile } from "./types";

export const mockJobs: JobOffer[] = [
  {
    id: "1",
    title: "CNC Machine Operator",
    site: "Bouarada",
    contractType: "CDI",
    department: "Production",
    seats: 3,
    description:
      "Operate and maintain CNC machines for precision automotive parts manufacturing.",
    requiredSkills: ["CNC Programming", "Quality Control", "Technical Drawing"],
    experienceYears: 1,
    showSalary: false,
    status: "open",
    deadline: "2026-03-25",
    createdAt: "2026-02-01T08:00:00Z",
    updatedAt: "2026-02-01T08:00:00Z",
  },
  {
    id: "2",
    title: "Quality Engineer",
    site: "Zaghouan",
    contractType: "CDI",
    department: "Quality Assurance",
    seats: 1,
    description:
      "Ensure product quality standards and implement continuous improvement processes.",
    requiredSkills: ["ISO 9001", "IATF 16949", "Six Sigma"],
    experienceYears: 2,
    showSalary: false,
    status: "open",
    deadline: "2026-03-20",
    createdAt: "2026-02-03T08:00:00Z",
    updatedAt: "2026-02-03T08:00:00Z",
  },
  {
    id: "3",
    title: "Production Intern",
    site: "Bouarada",
    contractType: "Stage",
    department: "Production",
    seats: 2,
    description:
      "Support production team with daily operations and process documentation.",
    requiredSkills: ["Mechanical Engineering", "AutoCAD", "Teamwork"],
    experienceYears: 0,
    showSalary: false,
    status: "open",
    deadline: "2026-04-01",
    createdAt: "2026-02-05T08:00:00Z",
    updatedAt: "2026-02-05T08:00:00Z",
  },
  {
    id: "4",
    title: "Maintenance Technician",
    site: "Zaghouan",
    contractType: "CDD",
    department: "Maintenance",
    seats: 2,
    description:
      "Perform preventive and corrective maintenance on production equipment.",
    requiredSkills: ["Electrical Systems", "PLC", "Preventive Maintenance"],
    experienceYears: 1,
    showSalary: false,
    status: "open",
    deadline: "2026-03-18",
    createdAt: "2026-02-07T08:00:00Z",
    updatedAt: "2026-02-07T08:00:00Z",
  },
  {
    id: "5",
    title: "Logistics Coordinator",
    site: "Bouarada",
    contractType: "CDI",
    department: "Logistics",
    seats: 1,
    description: "Coordinate inbound and outbound logistics operations.",
    requiredSkills: ["SAP", "Supply Chain", "Inventory Management"],
    experienceYears: 1,
    showSalary: false,
    status: "open",
    deadline: "2026-03-30",
    createdAt: "2026-02-09T08:00:00Z",
    updatedAt: "2026-02-09T08:00:00Z",
  },
  {
    id: "6",
    title: "Process Engineer",
    site: "Zaghouan",
    contractType: "CDI",
    department: "Engineering",
    seats: 1,
    description:
      "Develop and optimize manufacturing processes for automotive components.",
    requiredSkills: ["Lean Manufacturing", "CATIA", "Process Optimization"],
    experienceYears: 2,
    showSalary: false,
    status: "open",
    deadline: "2026-04-05",
    createdAt: "2026-02-11T08:00:00Z",
    updatedAt: "2026-02-11T08:00:00Z",
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-1",
    candidateId: "user-1",
    offerId: "1",
    status: "interview",
    createdAt: "2026-02-15T10:30:00Z",
    updatedAt: "2026-02-18T14:00:00Z",
    offer: mockJobs[0],
    interview: {
      id: "int-1",
      applicationId: "app-1",
      date: "2026-03-12",
      time: "10:00",
      location: "Schulte Tunisia - Bouarada Factory, Building A",
      type: "on-site",
      status: "scheduled",
      prepNotes: [
        "Réviser les bases de la programmation CNC",
        "Préparer des questions sur les objectifs de production",
        "Apporter des copies des certifications",
      ],
    },
  },
  {
    id: "app-2",
    candidateId: "user-1",
    offerId: "2",
    status: "reviewing",
    createdAt: "2026-02-20T16:45:00Z",
    updatedAt: "2026-02-25T11:00:00Z",
    offer: mockJobs[1],
  },
  {
    id: "app-3",
    candidateId: "user-1",
    offerId: "3",
    status: "accepted",
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-02-01T09:00:00Z",
    offer: mockJobs[2],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-1",
    title: "Entretien planifié",
    message:
      "Votre entretien pour le poste CNC Machine Operator a été planifié pour le 12 mars 2026.",
    type: "success",
    read: false,
    createdAt: "2026-03-05T09:00:00Z",
  },
  {
    id: "notif-2",
    userId: "user-1",
    title: "Candidature en cours d'examen",
    message:
      "Votre candidature pour le poste Quality Engineer est en cours d'examen par notre équipe.",
    type: "info",
    read: true,
    createdAt: "2026-02-25T11:00:00Z",
  },
  {
    id: "notif-3",
    userId: "user-1",
    title: "Nouvelle offre disponible",
    message:
      "Un nouveau poste correspondant à votre profil : Process Engineer à Zaghouan.",
    type: "info",
    read: false,
    createdAt: "2026-03-01T08:00:00Z",
  },
  {
    id: "notif-4",
    userId: "user-1",
    title: "Candidature acceptée",
    message:
      "Votre candidature pour le poste Production Intern a été acceptée.",
    type: "success",
    read: true,
    createdAt: "2026-02-01T09:00:00Z",
  },
];

export const mockProfile: UserProfile = {
  id: "user-1",
  name: "Ahmed Ben Ali",
  email: "ahmed.benali@email.com",
  phone: "+21698765432",
  role: "CANDIDATE",
  site: "Bouarada",
  experience: "3 years",
  skills: [
    "CNC Programming",
    "AutoCAD",
    "Quality Control",
    "Lean Manufacturing",
  ],
  cvUrl: "/cv/ahmed-benali.pdf",
};
